server:
  port: 8005
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    open-in-view: false
security:
  jwt:
    secret-key: _b3MKhBVzoPTJyiP2NmR2Ml_Lp62vmDr3dQwGq7FsO4
    expiration-time: 86400000
