spring:
  application:
    name: blog-back-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql


security:
  jwt:
    secret-key: tSI7NpFQ8fDHEtFK5v0YrUlnD/ffI84EUngT/qb8CmL4q/UZC5g1zfmC360Q9xvead++KjoDR/sJNTHjrjoh2Q==
    expiration-time: 86400000

